### ISSUE TITLE
cmake+doxygen seems to need CMP0057

### ISSUE THREAD

**Issue by misho104** [GM2Calc/GM2Calc#1]
Hi, with cmake 3.11.4 and doxygen 1.8.14 (both installed via Homebrew), `cmake` fails with the error msg

```
CMake Warning (dev) at /usr/local/Cellar/cmake/3.11.4/share/cmake/Modules/FindDoxygen.cmake:775 (if):
  Policy CMP0057 is not set: Support new IN_LIST if() operator.

CMake Error at /usr/local/Cellar/cmake/3.11.4/share/cmake/Modules/FindDoxygen.cmake:775 (if):
  if given arguments:
```

It seems to me that CMP0057 should be set `NEW` as
```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -6,6 +6,10 @@ if(NOT CMAKE_BUILD_TYPE)
   set(CMAKE_BUILD_TYPE Release)
 endif()

+if(POLICY CMP0057)
+  cmake_policy(SET CMP0057 NEW)
+
```

With this modification, `cmake`, `make` and `make doc` are run successfully.

**Comment by Expander** [comment]
Dear Sho Iwamoto,

many thanks for your report and your fix!  I've created the `fix-policy-CMP0057` branch, where I've applied your fix.  Would you mind checking if that branch builds ok?

Many thanks and best regards,
Alex

**Comment by misho104** [comment]
Hi Alex,
I've checked the branch is successfully built (`cmake` `make` and `make doc`).

Best,
Sho

**Comment by Expander** [comment]
Hi Sho,

many thanks for testing! I've merged the branch into master now, so your fix will go into the next release of GM2Calc.

Many thanks again for your contribution and best regards,
Alex
